Displays game with a few functions working
JamesBuabin14/sparta-global-project1 pull request #1
Opened 2018-02-06 15:29 UTC by JamesBuabin14

2018-02-06 15:31 UTC, JSChilds commented on index.html
> +    <script src="./js/jquery-3.3.1.min.js"></script>
This file has not been pushed up to the repository, therefore jQuery is not linked and none of your JavaScript works.

2018-02-06 15:32 UTC, JSChilds commented on js/app.js
> +
Don't leave in big, inconsistent spaces like this, it makes the code hard to read.

2018-02-06 15:32 UTC, JSChilds requested changes
Get your jQuery linked up and fix your spacing to make your code more readable.

2018-02-09 09:13 UTC, JSChilds commented on js/app.js
> +      // console.log(e.target);
Please remove ALL commented-out code and console.logs

2018-02-09 09:15 UTC, JSChilds commented on pages/game.html
> +    <span id="timer"></span>
Please change the font of these so they're easier to see.

2018-02-09 09:25 UTC, JSChilds requested changes
Please make changes requested in comments.

2018-02-09 09:33 UTC, JamesBuabin14 commented
Changes made, waiting to make new pull request to master branch

2018-02-09 09:45 UTC, JSChilds approved these changes

2018-02-09 09:45 UTC, merged